WIP/Broken: Attempt to cleanup ignored events
This commit starts down the path of cleaning up ignored events. It
breaks ignoring events, clearing the set of ignored events every 5
seconds.

The idea is to use `EKEventStore.event(withIdentifier:)` to see if
ignored event IDs still exist somewhere in the user's calendar, and if
they don't trim them from the set of ignored events to prevent unbounded
growth.

Initially ran into calendar permission issues like

> ERROR: Request access to specific EventKit entity types before
> attempting to retrieve EventKit objects.

when using `EKEventStore.calendarItem(withIdentifier:)`. Seemed
reasonable that the issue could be that since the `EKEventStore`
extension `accessCheck` asks for `.event`, not `.reminder`, that EK
might trip up on attempting to instantiate an `EKCalendarItem`.
Unfortunately, this error persists after converting to use of `EKEvent`
rather than `EKCalendarItem` all around the "ignore" feature.